mutation(
  $name:String!
  $duration:Int!
  $servings:Int!
  $img:String!
  $description:String!
  $ingredients:JSON!
  $steps:JSON!
  $category:ID!
  $autor:ID!
){
  createRecipe( 
  input:{
    data:{
      name:$name
      duration:$duration
      servings:$servings
      img:$img
      description:$description
      ingredients:$ingredients
      steps:$steps
      category:$category
      autor:$autor
    }
  }
  ){
    recipe{
      id
      name
      category{
        id
        name
      }
    }
  }
}